<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatestCommentsByPostId($numPostId)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.parentSocialEntity', 'p')
            ->andWhere('p.id = :post_id')
            ->setParameter('post_id', $numPostId)
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
