<?php

namespace AppBundle\Repository;

/**
 * DocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
