<?php

namespace AppBundle\Repository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByHouseId($houseId)
    {
        return $this->findBy(['id' => $houseId], ['createdAt' => 'desc']);
    }

    public function findAllUnitsInHouseById($numHouseId)
    {
        return $this->createQueryBuilder('h')
            ->leftJoin('h.units', 'u')
            ->andWhere('h.id = :house_id')
            ->setParameter('house_id', $numHouseId)
            ->orderBy('h.id', 'ASC')
            ->getQuery()
            ->getSingleResult();
    }

    public function findAllHouseUsersInHouseById($numHouseId)
    {
        return $this->createQueryBuilder('h')
            ->leftJoin('h.houseUsers', 'hu')
            ->andWhere('h.id = :house_id')
            ->setParameter('house_id', $numHouseId)
            ->orderBy('h.id', 'ASC')
            ->getQuery()
            ->getSingleResult();
    }
}
