<?php

namespace AppBundle\Repository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByHouseId($houseId)
    {
        return $this->findBy(array('id' => $houseId), array('createdAt' => 'desc'));
    }
}
