<?php

namespace AppBundle\Repository;

/**
 * ImportedDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
