<?php

namespace AppBundle\Repository;

/**
 * ImportedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
