<?php

namespace AppBundle\Repository;

/**
 * ImportedPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
