<?php

namespace AppBundle\Repository;

/**
 * ImportedHouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedHouseRepository extends \Doctrine\ORM\EntityRepository
{
}
