<?php

namespace AppBundle\Repository;

/**
 * ImportedUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
