<?php

namespace AppBundle\Repository;

/**
 * ImportSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportSourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSourceByApiKey($strApiKey)
    {
        return $this->createQueryBuilder('s')
            ->andWhere('s.apiKey = :apikey')
            ->setParameter('apikey', $strApiKey)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
