<?php

namespace AppBundle\Repository;

/**
 * ImportedHouseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedHouseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
