<?php

namespace AppBundle\Repository;

/**
 * ImportedUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedUserRepository extends \Doctrine\ORM\EntityRepository
{
}
