<?php

namespace AppBundle\Repository;

/**
 * ImportedBillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedBillRepository extends \Doctrine\ORM\EntityRepository
{
}
