<?php

namespace AppBundle\Repository;

/**
 * MalfunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MalfunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
