<?php

namespace AppBundle\Repository;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
