<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatestPostsInHouseById($numHouseId)
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.house', 'h')
            ->andWhere('h.id = :house_id')
            ->setParameter('house_id', $numHouseId)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
