<?php

namespace AppBundle\Repository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRegistrationByHash($strHash)
    {
        return $this->createQueryBuilder('r')
            ->andWhere('r.hash = :hash')
            ->andWhere('r.status = 1')
            ->setParameter('hash', $strHash)
            ->orderBy('r.id', 'ASC')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
