<?php

namespace AppBundle\Repository;

/**
 * UnitTenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTenantRepository extends \Doctrine\ORM\EntityRepository
{
}
