<?php

namespace AppBundle\Repository;

/**
 * UnitTenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTenantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUnitIdAndTenantId($numUnitID, $numHouseUserID)
    {
        return $this->createQueryBuilder('ut')
            ->andWhere('ut.tenant = :tenant_id')
            ->andWhere('ut.unit = :unit_id')
            ->setParameter('tenant_id', $numHouseUserID)
            ->setParameter('unit_id', $numUnitID)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
