# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  encoders:
    FOS\UserBundle\Model\UserInterface: sha512
    #CashbackCloud\CommonBundle\Entity\Translator: plaintext

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    api_key_user_provider:
      id: AppBundle\Security\ApiKeyUserProvider
    doctrine:
      entity:
        class: AppBundle:User
        property: apiKey

    in_memory:
      memory: ~

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    login:
      pattern:  ^/login$
      security: false
    #pattern:  ^/api/login
    #stateless: true
    #anonymous: true
    #json_login:
    #  check_path:               /api/login_check
    #  success_handler:          lexik_jwt_authentication.handler.authentication_success
    #  failure_handler:          lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern:   ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      simple_preauth:
        authenticator: AppBundle\Security\ApiKeyAuthenticator
      provider: api_key_user_provider

      guard:
        authenticators:
          - AppBundle\Security\TokenAuthenticator

      anonymous: ~
      json_login:
        check_path: /login
      # activate different ways to authenticate

      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
      http_basic: ~

      # https://symfony.com/doc/current/security/form_login_setup.html
      #form_login: ~
  #access_control:
  #  - { path: ^/units, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }