api_homepage:
  path:     /
  defaults: { _controller: ApiBundle:Default:index }
logout:
  path: /logout
api_get_houses:
  path: /houses
  defaults: { _controller: ApiBundle:Default:getHouses }
  methods: GET
api_get_house:
  path: /house/{id}
  defaults: { _controller: ApiBundle:Default:getHouseById }
  methods: GET
api_get_units:
  path: /units/{house_id}
  defaults: { _controller: ApiBundle:Default:getUnitsByHouse }
  methods: GET
api_get_unit:
  path: /unit/{unit_id}
  defaults: { _controller: ApiBundle:Default:getUnitById }
  methods: GET
api_get_house_users_by_house:
  path: /house/{house_id}/house-users
  defaults: { _controller: ApiBundle:Default:getHouseUsersByHouseId }
  methods: GET
api_get_house_users_by_unit:
  path: /unit/{unit_id}/house-users
  defaults: { _controller: ApiBundle:Default:getHouseUsersByUnitId }
  methods: GET
api_get_user:
  path: /user/{user_id}
  defaults: { _controller: ApiBundle:Default:getUserById , user_id: 0 }
  methods: GET
api_get_documents_by_house_id:
  path: /documents/{house_id}
  defaults: { _controller: ApiBundle:Default:getDocumentsByHouseId }
  methods: GET
api_get_house_user_by_id:
  path: /house-user/{house_user_id}
  defaults: { _controller: ApiBundle:Default:getHouseUserById }
  methods: GET
api_get_posts_by_house:
  path: /posts/{house_id}
  defaults: { _controller: ApiBundle:Default:getPostsByHouseId }
  methods: GET
api_get_malfunctions_by_house:
  path: /malfunctions/{house_id}
  defaults: { _controller: ApiBundle:Default:getMalfunctionsByHouseId }
  methods: GET
api_get_bills_by_unit:
  path: /bills/{unit_id}
  defaults: { _controller: ApiBundle:Default:getBillsByUnitId }
  methods: GET
api_post_post_to_house:
  path: /post/post
  defaults: { _controller: ApiBundle:Default:postPostToHouse }
  methods: POST
api_post_malfunction_to_house:
  path: /malfunction/post
  defaults: { _controller: ApiBundle:Default:postMalfunctionToHouse }
  methods: POST
api_post_comment_to_social_entity:
  path: /comment/post
  defaults: { _controller: ApiBundle:Default:postCommentToSocialEntity }
  methods: POST
api_get_comments_by_social_entity:
  path: /comments/{social_entity_id}
  defaults: { _controller: ApiBundle:Default:getCommentsBySocialEntityId }
  methods: GET
api_get_managers_by_house:
  path: /managers/{house_id}
  defaults: { _controller: ApiBundle:Default:getManagersByHouseId }
  methods: GET
api_get_balance_by_house:
  path: /balance/{house_id}
  defaults: { _controller: ApiBundle:Default:getBalanceByHouseId }
  methods: GET
api_get_detailed_balance_by_unit:
  path: /balance/unit/{unit_id}
  defaults: { _controller: ApiBundle:Default:getDetailedBalanceByUnitId }
  methods: GET
api_get_register_user:
  path: /registration
  defaults: { _controller: ApiBundle:Default:getRegistrationByToken }
  methods: POST
api_get_payment_methods:
  path: /payment-methods
  defaults: { _controller: ApiBundle:Default:getPaymentMethods }
  methods: GET

login:
  path:     /login
  defaults: { _controller: ApiBundle:Security:login }