services:
  #  _defaults:
  #    autowire: true
  #    autoconfigure: true
  #    public: true

  #  ApiBundle\:
  #    resource: '../../../ApiBundle/*'
  #    exclude: '../../../ApiBundle/{Entity,Repository}'
  response_handler:
    class: ApiBundle\Service\ResponseHandler
    arguments: ['@jms_serializer']