services:
  #  _defaults:
  #    autowire: true
  #    autoconfigure: true
  #    public: true

  #  ApiBundle\:
  #    resource: '../../../ApiBundle/*'
  #    exclude: '../../../ApiBundle/{Entity,Repository}'
  response_handler:
    class: ApiBundle\Service\ResponseHandler
    arguments: ['@jms_serializer']
  validation_handler:
    class: ApiBundle\Service\ValidationHandler
    arguments: ['@response_handler', '@doctrine.orm.entity_manager']

  #api.tokens.action_listener:
  #  class: ApiBundle\EventListener\TokenListener
  #  arguments: ['@doctrine.orm.default_entity_manager']
  #  tags:
  #    - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }