AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        createdAt:
            type: datetime
            column: created_at
        modifiedAt:
            type: datetime
            column: modified_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
