AppBundle\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: AppBundle\Repository\CommentRepository
    fields:
        userId:
            type: integer
            column: user_id
        content:
            type: text
        modifiedAt:
            type: datetime
            column: modified_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        user:
            targetEntity: User
            inversedBy: comments
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
