AppBundle\Entity\House:
  type: entity
  table: houses
  repositoryClass: AppBundle\Repository\HouseRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    countryCode:
      type: string
      length: '2'
      column: country_code
    region:
      type: string
      length: 255
      nullable: true
    postalCode:
      type: string
      length: 255
      column: postal_code
    city:
      type: string
      length: 255
      column: city
    street:
      type: string
      length: 255
      column: street
    building:
      type: string
      length: 255
      nullable: true
    unit:
      type: string
      length: 255
    lotNumber:
      type: string
      length: 255
      column: lot_number
    gpsLatitude:
      type: string
      length: 255
      column: gps_latitude
      nullable: true
    gpsLongitude:
      type: string
      length: 255
      column: gps_longitude
      nullable: true
    status:
      type: smallint
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
    isImported:
      type: boolean
      column: is_imported
      nullable: true
    taxNumber:
      type: string
      length: 64
      nullable: true
      column: tax_number
    foundingDate:
      type: date
      column: founding_date
      nullable: true
    bankAccountNumber:
      type: string
      length: 64
      nullable: true
      column: bank_account_number
    ownershipSum:
      type: float
      nullable: true
      column: ownership_sum
  oneToMany:
    documents:
      targetEntity: Document
      mappedBy: house
    units:
      targetEntity: Unit
      mappedBy: house
    houseUsers:
      targetEntity: HouseUser
      mappedBy: house
    posts:
      targetEntity: Post
      mappedBy: house
    malfunctions:
      targetEntity: Malfunction
      mappedBy: house
  manyToOne:
    houseManager:
      targetEntity: HouseUser
      inversedBy: houses
      joinColumn:
        name: house_manager_id
        referencedColumnName: id
  oneToOne:
    importedHouse:
      targetEntity: ImportedHouse
      inversedBy: house
      joinColumn:
        name: imported_house_id
        referencedColumnName: id