AppBundle\Entity\ImportedUser:
  type: entity
  table: imported_users
  repositoryClass: AppBundle\Repository\ImportedUserRepository
  fields:
    registrationDate:
      type: datetime
      column: registration_date
      nullable: true
    firstName:
      type: string
      length: 255
      column: first_name
    lastName:
      type: string
      length: 255
      column: last_name
    dateOfBirth:
      type: date
      column: date_of_birth
      nullable: true
    placeOfBirth:
      type: string
      length: 255
      column: place_of_birth
      nullable: true
    bio:
      type: text
      column: Bio
      nullable: true
    sex:
      type: integer
      column: Sex
      nullable: true
    phoneNumber:
      type: string
      length: 255
      column: phone_number
      nullable: true
    localPhoneNumber:
      type: string
      length: 255
      column: local_phone_number
      nullable: true
    idNumber:
      type: integer
      nullable: true
      column: id_number
    officialAddress:
      type: string
      length: 255
      column: official_address
      nullable: true
    currentLocation:
      type: string
      length: 255
      column: current_location
      nullable: true
    joinToken:
      type: string
      length: 255
      column: join_token
      nullable: true
  lifecycleCallbacks: {  }
