AppBundle\Entity\ImportSource:
  type: entity
  table: import_source
  repositoryClass: AppBundle\Repository\ImportSourceRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    apiKey:
      type: string
      length: 255
      column: api_key
    isActive:
      type: boolean
      column: is_active
    email:
      type: string
      length: 255
    username:
      type: string
      length: 255
  oneToMany:
    importedEntities:
      targetEntity: ImportedEntity
      mappedBy: importSource
  lifecycleCallbacks: {  }
