AppBundle\Entity\Manager:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ManagerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        website:
            type: string
            length: 255
        logoImage:
            type: string
            length: 255
            column: logo_image
    lifecycleCallbacks: {  }
