AppBundle\Entity\Payment:
  type: entity
  table: payment
  repositoryClass: AppBundle\Repository\PaymentRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    paymentDate:
      type: datetime
      column: payment_date
    bookingDate:
      type: datetime
      column: booking_date
    receiptNumber:
      type: string
      length: 255
      column: receipt_number
    amount:
      type: integer
    status:
      type: smallint
  manyToOne:
    paymentMethod:
      targetEntity: PaymentMethod
      inversedBy: payments
      joinColumn:
        name: payment_method_id
        referencedColumnName: id
    unit:
      targetEntity: Unit
      inversedBy: payments
      joinColumn:
        name: unit_id
        referencedColumnName: id
    user:
      targetEntity: User
      inversedBy: payments
      joinColumn:
        name: user_id
        referencedColumnName: id
    houseUser:
      targetEntity: HouseUser
      inversedBy: payments
      joinColumn:
        name: house_user_id
        referencedColumnName: id
  oneToOne:
    importedPayment:
      targetEntity: ImportedPayment
      inversedBy: payment
      joinColumn:
        name: imported_payment_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
