AppBundle\Entity\Reaction:
    type: entity
    table: reaction
    repositoryClass: AppBundle\Repository\ReactionRepository

    fields:
        reactionType:
            type: smallint
            column: reaction_type
    lifecycleCallbacks: {  }
