AppBundle\Entity\Registration:
    type: entity
    table: registration
    repositoryClass: AppBundle\Repository\RegistrationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: string
            length: 255
        status:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        user:
            targetEntity: User
            inversedBy: registrations
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
