AppBundle\Entity\SocialEntity:
    type: entity
    table: social_entities
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        social_entity: AppBundle\Entity\SocialEntity
        post: AppBundle\Entity\Post
        comment: AppBundle\Entity\Comment
        document: AppBundle\Entity\Document
        malfunction: AppBundle\Entity\Malfunction
        reaction: AppBundle\Entity\Reaction
    repositoryClass: SocialEntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: socialEntity
        comments:
            targetEntity: Comment
            mappedBy: socialEntity
    lifecycleCallbacks: {  }
