AppBundle\Entity\SocialEntity:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        socialEntity: SocialEntity
        post: Post
        comment: Comment
        document: Document
        malfunction: Malfunction
        reaction: Reaction
    table: social_entity
    repositoryClass: AppBundle\Repository\SocialEntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
