AppBundle\Entity\Tenant:
<<<<<<< HEAD
  type: entity
  table: tenant
  repositoryClass: AppBundle\Repository\TenantRepository
  fields:
    localContactNumber:
      type: string
      length: 255
      nullable: true
      column: local_contact_number
  oneToMany:
    unitTenant:
      targetEntity: UnitTenant
      mappedBy: tenant
  lifecycleCallbacks: {  }
=======
    type: entity
    table: tenant
    repositoryClass: AppBundle\Repository\TenantRepository
    fields:
        localContactNumber:
            type: string
            length: 255
            nullable: true
            column: local_contact_number
    oneToOne:
        unitTenant:
            targetEntity: UnitTenant
            mappedBy: tenant
    lifecycleCallbacks: {  }
>>>>>>> feature/SalesAndManagers
