AppBundle\Entity\Unit:
  type: entity
  table: unit
  repositoryClass: AppBundle\Repository\UnitRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    building:
      type: string
      length: 255
    floor:
      type: smallint
    door:
      type: smallint
    floorArea:
      type: float
      column: floor_area
    unitType:
      type: smallint
      column: unit_type
    balance:
      type: integer
      nullable: true
    houseShare:
      type: string
      length: 255
      column: house_share
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    isImported:
      type: boolean
      column: is_imported
      nullable: true
  oneToMany:
    payments:
      targetEntity: Payment
      mappedBy: unit
    bills:
      targetEntity: Bill
      mappedBy: unit
    orders:
      targetEntity: Order
      mappedBy: unit
    tenants:
      targetEntity: UnitTenant
      mappedBy: unit
  oneToOne:
    importedUnit:
      targetEntity: ImportedUnit
      inversedBy: unit
      joinColumn:
        name: imported_unit_id
        referencedColumnName: id
  manyToOne:
    house:
      targetEntity: House
      inversedBy: units
      joinColumn:
        name: house_id
        referencedColumnName: id
  lifecycleCallbacks: {  }

