AppBundle\Entity\Unit:
    type: entity
    table: unit
    repositoryClass: AppBundle\Repository\UnitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        building:
            type: string
            length: 255
        floor:
            type: smallint
        door:
            type: smallint
        floorArea:
            type: float
            column: floor_area
        type:
            type: smallint
        balance:
            type: integer
        houseShare:
            type: string
            length: 255
            column: house_share
    oneToMany:
        payments:
            targetEntity: Payment
            mappedBy: unit
    lifecycleCallbacks: {  }
