AppBundle\Entity\UnitTenant:
    type: entity
    table: unit_tenant
    repositoryClass: AppBundle\Repository\UnitTenantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: smallint
        ownershipShare:
            type: string
            length: 255
            column: ownership_share
        status:
            type: smallint
    lifecycleCallbacks: {  }
