AppBundle\Entity\UnitTenant:
    type: entity
    table: unit_tenant
    repositoryClass: AppBundle\Repository\UnitTenantRepository
    id:
<<<<<<< HEAD
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    type:
      type: smallint
      nullable: true
    ownershipShare:
      type: string
      length: 255
      column: ownership_share
      nullable: true
    status:
      type: smallint
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
  oneToMany:
    units:
      targetEntity: Unit
      mappedBy: unitTenant
  manyToOne:
    tenant:
      targetEntity: Tenant
      inversedBy: unitTenant
      joinColumn:
        name: tenant_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
=======
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: smallint
        ownershipShare:
            type: string
            length: 255
            column: ownership_share
        status:
            type: smallint
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    oneToMany:
        units:
            targetEntity: Unit
            mappedBy: unitTenant
    oneToOne:
        tenant:
            targetEntity: Tenant
            inversedBy: unitTenant
            joinColumn:
                name: tenant_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
>>>>>>> feature/SalesAndManagers
