AppBundle\Entity\User:
  type: entity
  table: users
  repositoryClass: AppBundle\Repository\UserRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    registrationDate:
      type: datetime
      column: registration_date
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    firstName:
      type: string
      length: 255
      column: first_name
    lastName:
      type: string
      length: 255
      column: last_name
    dateOfBirth:
      type: date
      column: date_of_birth
    placeOfBirth:
      type: string
      length: 255
      column: place_of_birth
    bio:
      type: text
      column: Bio
    sex:
      type: integer
      column: Sex
    phoneNumber:
      type: string
      length: 255
      column: phone_number
      nullable: true
    localPhoneNumber:
      type: string
      length: 255
      column: local_phone_number
    idNumber:
      type: integer
      nullable: true
      column: id_number
    officialAddress:
      type: string
      length: 255
      column: official_address
    currentLocation:
      type: string
      length: 255
      column: current_location
    joinToken:
      type: string
      length: 255
      column: join_token
      nullable: true
    apiKey:
      type: string
      length: 255
      column: api_key
    phoneConformationSentAt:
      type: datetime
      nullable: true
      column: phone_confirm_sent_at
    phoneConformationCode:
      type: string
      nullable: true
      column: phone_confirm_code
    profileImage:
      type: string
      nullable: true
      column: profile_image
    facebook:
      type: string
      length: 255
      column: facebook
    twitter:
      type: string
      length: 255
      column: twitter
    instagram:
      type: string
      length: 255
      column: instagram
  oneToMany:
    documents:
      targetEntity: Document
      mappedBy: user
    comments:
      targetEntity: Comment
      mappedBy: user
    notifications:
      targetEntity: Notification
      mappedBy: user
    payments:
      targetEntity: Payment
      mappedBy: user
    orders:
      targetEntity: Order
      mappedBy: user
    registrations:
      targetEntity: Registration
      mappedBy: user
    posts:
      targetEntity: Post
      mappedBy: user
    houseUsers:
      targetEntity: HouseUser
      mappedBy: user
    reactions:
      targetEntity: Reaction
      mappedBy: user
  manyToMany:
    permissions:
      targetEntity: AppBundle\Entity\Permission
      inversedBy: users
      joinTable:
        name: users_permissions
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          permission_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }
