<?php

namespace AppBundle\Entity;

/**
 * SocialEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
